### ISSUE TITLE
make menuconfig 中缺少argon 主题

### ISSUE THREAD

**Issue by wyap-echo** [jerrykuku/openwrt-package#1]
添加到feed后 再次安装更新feed后 在make menuconfig 中的主题插件里找不到argon 主题插件
Updating feed 'jerryk' from 'https://github.com/jerrykuku/openwrt-package' ...
正克隆到 './feeds/jerryk'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
展开对象中: 100% (5/5), 完成.
子模组 'lua-maxminddb'（https://github.com/jerrykuku/lua-maxminddb.git）未对路径 'lua-maxminddb' 注册
子模组 'luci-app-jd-dailybonus'（https://github.com/jerrykuku/luci-app-jd-dailybonus.git）未对路径 'luci-app-jd-dailybonus' 注册
子模组 'luci-app-vssr'（https://github.com/jerrykuku/luci-app-vssr.git）未对路径 'luci-app-vssr' 注册
子模组 'luci-theme-argon'（https://github.com/jerrykuku/luci-theme-argon.git）未对路径 'luci-theme-argon' 注册
子模组 'node-request'（https://github.com/jerrykuku/node-request.git）未对路径 'node-request' 注册
正克隆到 '/home/wyap/lede/feeds/jerryk/lua-maxminddb'...
正克隆到 '/home/wyap/lede/feeds/jerryk/luci-app-jd-dailybonus'...
正克隆到 '/home/wyap/lede/feeds/jerryk/luci-app-vssr'...
正克隆到 '/home/wyap/lede/feeds/jerryk/luci-theme-argon'...
正克隆到 '/home/wyap/lede/feeds/jerryk/node-request'...
子模组路径 'lua-maxminddb'：检出 '20d1459ec617eb0029ccf3e4b5db62bc339529db'
子模组路径 'luci-app-jd-dailybonus'：检出 'b0de7d90a4448943caa279de6b4d633e335910fb'
子模组路径 'luci-app-vssr'：检出 '696477e0439dd95fc115ef7374c0993c926af00b'
子模组路径 'luci-theme-argon'：检出 'd4b25413a37cc03c0cf630ae291d3527a9fd0f6f'
子模组路径 'node-request'：检出 'b6de1f42e18a239ea95c9ed3af0dce385e555164'
Create index file './feeds/jerryk.index'

**Comment by jerrykuku** [comment]
可能是和lean 目录中的文件有冲突，所以我修改了 argon theme的名称。请重新 ./scripts/feeds update -a  并 ./scripts/feeds install -a 应该可以找到argon主题

**Comment by wyap-echo** [comment]
谢谢老哥 搞定了
